name: tweetclassify
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - datasets<4.0.0
    - transformers
    - scikit-learn
    - ollama
    - jupyter
    - torch